# Generated by Django 4.2.7 on 2025-09-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('GASTRONOMIA', 'Gastronomía'), ('PATRIMONIO_ARQUEOLOGICO', 'Patrimonio Arqueológico'), ('FLORA_MEDICINAL', 'Flora Medicinal'), ('LEYENDAS_Y_TRADICIONES', 'Leyendas y Tradiciones')], max_length=50)),
                ('confianza', models.FloatField()),
                ('descripcion', models.TextField()),
                ('contexto_cultural', models.TextField()),
                ('periodo_historico', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('significado', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultural_items/')),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemento Cultural',
                'verbose_name_plural': 'Elementos Culturales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CulturalAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_response', models.TextField()),
                ('processing_time', models.FloatField()),
                ('api_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultural_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cultural.culturalitem')),
            ],
            options={
                'verbose_name': 'Log de Análisis Cultural',
                'verbose_name_plural': 'Logs de Análisis Cultural',
            },
        ),
    ]
