# Generated by Django 4.2.7 on 2025-09-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultural', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalitem',
            name='imagen_base64',
        ),
    ]
