# Generated by Django 4.2.7 on 2025-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural', '0002_remove_culturalitem_imagen_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalitem',
            name='categoria',
            field=models.CharField(choices=[('GASTRONOMIA', 'Gastronomía'), ('PATRIMONIO_ARQUEOLOGICO', 'Patrimonio Arqueológico'), ('FLORA_MEDICINAL', 'Flora Medicinal'), ('LEYENDAS_Y_TRADICIONES', 'Leyendas y Tradiciones'), ('FESTIVIDADES', 'Festividades'), ('DANZA', 'Danza'), ('MUSICA', 'Música'), ('VESTIMENTA', 'Vestimenta'), ('ARTE_POPULAR', 'Arte Popular'), ('NATURALEZA_CULTURAL', 'Naturaleza/Cultural'), ('OTRO', 'Otro')], max_length=50),
        ),
    ]
