# Generated by Django 4.2.7 on 2025-11-10 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultural', '0003_alter_culturalitem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('CORRECCION', 'Corrección de análisis incorrecto'), ('NUEVO_ELEMENTO', 'Nuevo elemento cultural')], default='CORRECCION', max_length=20)),
                ('motivo', models.TextField(help_text='Razón del reporte')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('GASTRONOMIA', 'Gastronomía'), ('PATRIMONIO_ARQUEOLOGICO', 'Patrimonio Arqueológico'), ('FLORA_MEDICINAL', 'Flora Medicinal'), ('LEYENDAS_Y_TRADICIONES', 'Leyendas y Tradiciones'), ('FESTIVIDADES', 'Festividades'), ('DANZA', 'Danza'), ('MUSICA', 'Música'), ('VESTIMENTA', 'Vestimenta'), ('ARTE_POPULAR', 'Arte Popular'), ('NATURALEZA_CULTURAL', 'Naturaleza/Cultural'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('contexto_cultural', models.TextField()),
                ('periodo_historico', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('significado', models.TextField()),
                ('confianza', models.FloatField(default=0.85, help_text='Nivel de confianza sugerido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas del administrador')),
                ('created_cultural_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_report', to='cultural.culturalitem')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Cultural',
                'verbose_name_plural': 'Reportes Culturales',
                'ordering': ['-created_at'],
            },
        ),
    ]
